# .github/workflows/python-tests.yml
name: CI                               # Name of the workflow in GitHub Actions tab

on: [push, pull_request]               # Run on every push and pull request

jobs:
  test:
    runs-on: ubuntu-latest             # GitHub's Ubuntu runner

    steps:
      - uses: actions/checkout@v4      # 1️⃣ Check out repository code

      - uses: actions/setup-python@v5  # 2️⃣ Set up Python 3.11
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4️⃣ Run tests using pytest
      - name: Run tests
        run: pytest -q

      # 5️⃣ Run linting using flake8
      - name: Lint with flake8
        run: flake8 src tests


